version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    container_name: bank_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hayatdb12
      - POSTGRES_DB=simple_bank
    ports:
      - "5436:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:hayatdb12@postgres:5432/simple_bank?sslmode=disable

    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]