apiVersion: apps/v1
kind: deployment 

metadata:
  name: simple-bank-api-deployment 
  labels:
    app: simple-bank-api 

spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api 
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 2345.dkr.ecr.ap-southeast-2.amazonaws.com/simplebank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 50051
              name: grpc-server 

