# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      image: postgres:13
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: hayatdb12
        POSTGRES_DB: simple_bank
      options: >-
        --health--cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
        


    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        
      - name: Run migrations
        run: make migrateup


      - name: Test
        run: make test
